# CLA check disabled - rdkcentral workflow requires access to rdkcentral/cla_signatures repo
name: "CLA"

permissions:
  contents: write  # Changed from 'read' to 'write' to allow creating signature file
  pull-requests: write
  actions: write
  statuses: write

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  CLA-Lite:
    name: "Signature"
    permissions:
      contents: write
      pull-requests: write
      actions: write
      statuses: write
    uses: rdkcentral/cmf-actions/.github/workflows/cla.yml@v1
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_ASSISTANT }}
